### PR TITLE
initial review for structure + simple zk, thrift and curator wrapper classes

### PR DESCRIPTION
**Pull request by bpodgursky**
@khe this isn't a real PR since the code is all in master, but I couldn't figure out a better way of setting up a review.  so whatever.

This isn't even close to done, but I have a few utilities working; most of my work so far has been trying to import and test the Go libraries for ZooKeeper, Thrift, and Curator (high-level ZooKeeper library), and start building some tools around them which mirror what Hank uses internally in Java.

I made Hank generate Go thrift models, you can find them here: https://github.com/LiveRamp/hank/tree/master/hank-core/src/main/go/hank.  This uses those generated types (pulled in via Glide)

So basically, the main parts so far are

- map_partition_server and map_partition_server_test, where I set up a simple thrift server / client pair and test them out.   not that exciting, but I wanted to confirm it worked.

- coordinator.go, zk_coordinator.go, and zk_coordinator_test.go  this is basically the logic wrapper around ZooKeeper, and a lot of the implementation in this project will be here.  I'm essentially recreating this class and the chain of models it indexes into: https://github.com/LiveRamp/hank/blob/master/hank-core/src/main/java/com/liveramp/hank/coordinator/zk/ZooKeeperCoordinator.java

- zk_tools_test.go tests some of the tools that zk_coordinator will use, specifically ZkWatchedMap and ZkWatchedNode.  essentially these are in-memory data structures which stay synchronized with the underlying zk structures.

I hadn't written a line of Go until 5 days ago, so please tear this apart on everything that looks awful (code style, packaging conventions, language features I'm missing, etc etc).  Most of the horror shows in here are from me trying to build data structures in a  language without generics, I'm really hoping there's a solution than my current one (see: cast.go).

No rush, review whenever you have a chance.  Will keep working in the meantime.

### CODE REVIEW

**Comment by khe** [comment]
You may want to quickly go through: https://github.com/golang/go/wiki/CodeReviewComments first. 

- Code structure: glide part looks good, but I won't worry about dependency yet for a starter project. For hank-go-client, I am expecting a structure like `/src/github.com/bpodgursky/hank-go-client`.
 It helps others to `go get` the client. ( see https://golang.org/doc/code.html)
- Format: run `go fmt` to clean up the formatting. Not sure if you are using an IDE or not. If you are using Intellij, follow this setup: http://stackoverflow.com/questions/33774950/execute-gofmt-on-file-save-in-intellij
- Packages: We probably don't need that many packages.  Also, it is not necessary to have `hank_` prefixes for package naming. Consider: 1. combine `coordinator` and `hank_zk` 2. move `fixtures` and `mock` to corresponding packages. 3. avoid `util` package  4. It probably makes sense to just have package `hank-go-client`. 

- Comments: please comment every function that is supposed to be used outside of the package (AKA all those starting with upper case).
-  `hank_iface`: Not like java, we don't need one file per type. We can group them into one `interface.go`. 

- mocking: we use https://github.com/vektra/mockery and pretty happy about it so far.  

I will stop here and go learn some thrift before coming back to this CR.

**Comment by khe** [comment]
Also, CC @joshk0

**Comment by bpodgursky** [comment]
@khe ok, I've reformatted everything and fixed the src/ package naming.   I've changed the package names to not include hank scoping.  I've also consolidated a number of the files.

I think I disagree about the package consolidation though.  Everything currently packaged differently either has different external dependencies or is generic of hank:

- iface depends only on thrift (which is unavoidable because of the types).  this lets us create non-zk impls of the coordinator later.
- coordinator has the zk-dependent implementations of those interfaces
- fixtures are test-only code, and don't need to be included or compiled for production builds
- partition-server impls don't depend on zk, and does not need to be included for the client build
- serializers has generic thrift helpers (no dependency on Hank specifics)
- watched_structs has generic curator helper structs (no dependency on Hank specifics)

It might be a bit reflexive, but we've had had megaprojects in the past and it was always a enormous PITA to separate out generic components we could open-source or make available to other teams without dragging along a billion dependencies.  I'd rather start off with better separation of components than try to untangle it later.  Let me know if you think I'm way off the mark here, happy to discuss more.

**Comment by khe** [comment]
## package structure

1. You explained each package very well in your last comment. I now have a better understanding of why it was structured this way. After reading through this review, If you decide to keep the packages, could you please add these explanations as comments in the code? You can refer to [this](https://github.com/golang/go/wiki/Comments) when commenting on packages.

2. `coordinator` - rename to zkcoordinator? Then you can eliminate all zk_ prefixes of the files in that package. 

3. `hank_type` - remove? I don't think generated code should be checked in. Instead, HANK repo should be included as a dependency or submodule. A script or instruction needs to be provided to the user to generate hank types. This way, hank-go-client can easily adapt to any change in the hank api in the future. 

4. `serializers` - rename to `thriftext`? (short for thrift extension, which is a pretty common way of naming go packages)

5. `watched_structs` 
    1. rename to `curatorext`? 
    2. Since it is an extension of curator, the zk_ prefixes are redundant. 
    3. `zk_tools_test.go`
        1. it should not have dependency on iface
    	2. there should be different test files for different files. So watched_nodes_test.go, zk_utils_test.go... tec. If you find it hard to break up the tests, maybe there should be just one source file: watched.go, watched_test.go. 

6. `main` - rename to `examples`? 

7. `hank-client` - two proposals here: 
    1. rename `hank-client` to `client`, `NewHankSmartClient` to `New`. (since I don't find the non-smart version). When a user calls it, he'd be calling `client.New()`.
    2. rename `hank-client` to `hank`, `NewHankSmartClient` to `NewClient`. When a user calls it, he'd be calling `hank.NewClient()`
 
8. package consolidation. _Optional - I am trying to convince you but you don't need to be convinced :)._ 

Let's look at some similar packages first:   
   * [etcd-client](https://github.com/coreos/etcd/tree/master/client)
   * [redis-client](https://github.com/go-redis/redis)
   * [memcache-client](https://github.com/bradfitz/gomemcache)
   * [zookeeper-client](https://github.com/samuel/go-zookeeper)
As you can see, they all use very flat package structure. I am pretty sure it is a "Go thing". 
  
>  "Packages only really make sense in the context of a separate program which uses them. " 

from [introduction to go](https://www.golang-book.com/books/intro/11) This is the general guideline.

Following this guideline, `hank_client` is the only package that makes sense at the first glance. `coordinator`, `iface`, `watch_structs` and `fixtures` are implementation details of the client. I don't see they can be used outside of HANK. It doesn't make sense to make them an independent package because they can't be used as an independent package. It is a legit concern that tools other than zookeeper could be used for coordination later. But I don't think that outweighs the above guideline.

`serializers` in the other hand could be used externally. But it is small enough that can be separated out easily later if needed. 

## Encapsulation

I'd like to emphasize on encapsulation: ONLY those methods that are expected to be called by the users should be exposed (start with upper case letters)

One practice that I found useful in the past is to go through all the exposed functions and comment on ALL of them. When writing the comment, one would be naturally thinking about how and why the user should call the function. Lowercase those that are not supposed to be exposed. 

## `cast.go`
You don't have to do this. It seems to me you are trying to cast two different things here. 
1. cast an interface to another, which is not necessary. For example   
```
func (p *ZkCoordinator) GetDomain(domain string) (iface.Domain) {
	return iface.AsDomain(p.domains.Get(domain))
}
```
could be changed to: 
```
func (p *ZkCoordinator) GetDomain(domain string) iface.Domain {
	p.domains.Get(domain)
}
```
I think even the `GetDomain` function is redundant. We can simply use 
```
val domain = zkCoordinator.Get(domainStr) 
```
It would panic down the line if the returned interface isn't as expected. That's fine. We will get similar panics if we try to cast anyway. 

The use of _interface_ in Go is much more flexible than Java.  

2. cast an interface to a struct, which is generated by thrift. 
Instead of casting, I suggest you create interfaces that those thrift types would implement, very much like what you did with Coordinator, DomainGroup, etc, where you tried to abstract away from zookeeper implementation. If you do this, combined with #1 above, these whole casting codes are eliminated. 

Please let me know if these make sense.

**Comment by bpodgursky** [comment]
Thanks @khe  I've responded to or discussed most of these.  (3) is totally correct, I just checked the code in directly at the moment because the thrift+Go generation process was a mess and I didn't want to be blocked on it.  I'll check with Davin to see how far he got with the other spruce thrift stuff.

Will take another pass at encapsulation in a few days.

**Pull request closed without merging**
